# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tytul')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created', models.DateTimeField(verbose_name='Data dodania')),
                ('finished', models.DateTimeField(verbose_name='Termin zakonczenia')),
                ('assign', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tytul')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created', models.DateTimeField(verbose_name='Data dodania')),
                ('finished', models.DateTimeField(verbose_name='Termin zakonczenia')),
                ('assign', models.CharField(max_length=100)),
            ],
        ),
    ]
