# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_done_wip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='done',
            new_name='donejob',
        ),
    ]
