# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20160407_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='flag',
            field=models.CharField(default='todo', max_length=4),
        ),
    ]
