# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('lists', '0004_jobs_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='flag',
            field=models.CharField(choices=[('1', 'done'), ('2', 'wip'), ('3', 'todo')], default='todo', max_length=4),
        ),
    ]
